version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: autosalon-db
    environment:
      POSTGRES_DB: autosalon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"